server:
  port: 9000
  servlet:
    context-path: /advertise
spring:
  application:
    name: advertise-service
  datasource:
    url: jdbc:mysql://localhost:3306/advertise
    username: root
    password: root
  jpa:
    hibernate:
     ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
        namingStrategy: org.hibernate.cfg.PhysicalNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka